### PR TITLE
added text to athava's code by pranav

### PR DESCRIPTION
**Pull request by MrPranav1800**
accept the pull request

### CODE REVIEW

**Review by f1r3w41l — CHANGES_REQUESTED** [review]
Please add one more print with your name and Roll no.

**Review by f1r3w41l — APPROVED** [review]
Okay Well Done Buddy 🍡

**Comment by MrPranav1800** [comment]
the changes you requested has been done

**Comment by f1r3w41l** [comment]
okay now the code's ready.

**Pull request merged**
